---
basePath: "/"
paths:
  /accounts/historicalBalances:
    get:
      summary: "Get Historical Balances"
      deprecated: false
      produces:
      - "application/json;charset=UTF-8"
      description: "The historical balances service is used to retrieve the historical balances for an account or a user.<br>Historical balances are daily (D), weekly (W), and monthly (M). <br>The interval input should be passed as D, W, and M to retrieve the desired historical balances. The default interval is daily (D). <br>When no account id is provided, historical balances of the accounts that are active, to be closed, and closed are provided in the response. <br>If the fromDate and toDate are not passed, the last 90 days of data will be provided. <br>The fromDate and toDate should be passed in the YYYY-MM-DD format. <br>The date field in the response denotes the date for which the balance is requested.<br>includeCF needs to be sent as true if the customer wants to return carried forward balances <br>for a date when the data is not available. <br>asofDate field in the response denotes the date as of which the balance was updated for that account.<br>When there is no balance available for a requested date and if includeCF is sent as true, the previous <br>date for which the balance is available is provided in the response. When there is no previous <br>balance available, no data will be sent. <br>"
      operationId: "getHistoricalBalances"
      responses:
        200:
          schema:
            $ref: "https://api.swaggerhub.com/domains/Yodlee-POC/AccountHistoricalBalancesResponse/1.0.0#/definitions/AccountHistoricalBalancesResponse"
          description: "OK"
        400:
          schema:
            $ref: "https://api.swaggerhub.com/domains/Yodlee-POC/YodleeError/1.0.0#/definitions/YodleeError"
          description: "Y800 : Invalid value for accountId<br>Y800 : Invalid value for fromDate<br>Y800 : Invalid value for toDate<br>Y809 : Invalid date range<br>Y800 : Invalid value for interval<br>Y802 : Future date not allowed"
        401:
          description: "Unauthorized"
        404:
          description: "Not Found"
      parameters:
      - in: "query"
        allowEmptyValue: false
        name: "accountId"
        description: "accountId"
        type: "string"
        required: false
      - in: "query"
        allowEmptyValue: false
        name: "fromDate"
        description: "from date for balance retrieval (YYYY-MM-DD)"
        type: "string"
        required: false
      - in: "query"
        allowEmptyValue: false
        name: "includeCF"
        description: "Consider carry forward logic for missing balances"
        type: "boolean"
        required: false
      - in: "query"
        allowEmptyValue: false
        name: "interval"
        description: "D-daily, W-weekly or M-monthly"
        type: "string"
        required: false
      - in: "query"
        allowEmptyValue: false
        name: "skip"
        format: "int32"
        description: "skip (Min 0)"
        type: "integer"
        required: false
      - in: "query"
        allowEmptyValue: false
        name: "toDate"
        description: "toDate for balance retrieval (YYYY-MM-DD)"
        type: "string"
        required: false
      - in: "query"
        allowEmptyValue: false
        name: "top"
        format: "int32"
        description: "top (Max 500)"
        type: "integer"
        required: false
      tags:
      - "Accounts"
swagger: "2.0"
info:
  license:
    name: "Yodlee Developer License"
    url: "https://developer.yodlee.com/legal#_License"
  contact:
    email: "developer@yodlee.com"
  description: "This file describes the Yodlee Platform APIs, using the swagger notation. You can use this swagger file to generate client side SDKs to the Yodlee Platform APIs for many different programming languages. You can generate a client SDK for Python, Java, javascript, PHP or other languages according to your development needs. For more details about our APIs themselves, please refer to https://developer.yodlee.com/Yodlee_API/."
  termsOfService: "https://developer.yodlee.com/legal"
  title: "Get HistoricalBalance APIs"
  version: "1.1.0"
tags:
- name: "Accounts"
  description: "Accounts API"